### ISSUE TITLE
Add all the example programs and files from the advent demo to the Docker image

### ISSUE THREAD

**Issue by phochste** [LibreCat/docker-catmandu#2]
Unix tools:
- man
- cal
- nano
- vi
- curl
- wget
- perl-doc
- cpanm

**Comment by vpeil** [comment]
yes, sir. where can I find the files from the advent demo?

**Comment by phochste** [comment]
Added to the 'dev' branch

**Comment by vpeil** [comment]
finished, all requried tools are included. With the trade-off of image size....
